# Generated by Django 5.1.1 on 2024-09-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='store/images')),
                ('Precio', models.IntegerField()),
            ],
        ),
    ]
