# Generated by Django 5.1.1 on 2024-09-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
