# Generated by Django 5.1.1 on 2024-09-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0002_rename_precio_producto_precio_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='video',
            field=models.FileField(blank=True, upload_to='store/videos'),
        ),
    ]
